discodeit:
  storage:
    type: local
    local:
      root-path: ./storage
  servlet:
    multipart:
      max-file-size: 10MB       # 개별 파일 당 최대 용량 임시 설정
      max-request-size: 10MB

spring:
  profiles:
    active: dev # 일단 dev yaml로 실행되게 설정

  jpa:
    open-in-view: false
    show-sql: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        default_batch_fetch_size: 50 # 추가함.
        # 메시지 레포에서 entitygraph로다가 attachments도 들고오니까
        # 쿼리가 엄청 길어지길래 다른 방법 찾아보다가 batch 쓰는 방식으로 접근해 봄.
        # pageable 사이즈랑 동일하게 50으로 설정함.
        format_sql: true
        highlight_sql: true
        use_sql_comments: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace


